apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoints-prom-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoints-prom-exporter
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["namespaces", "events", "endpointslices", "endpoints", "services"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoints-prom-exporter
subjects:
- kind: ServiceAccount
  name: endpoints-prom-exporter
  namespace: default
roleRef:
  kind: ClusterRole
  name: endpoints-prom-exporter
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoints-prom-exporter
  labels:
    app: endpoints-prom-exporter
  # annotations:
  #   prometheus.io/port: 9153
  #   prometheus.io/scrape: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoints-prom-exporter
  template:
    metadata:
      labels:
        app: endpoints-prom-exporter
    spec:
      serviceAccountName: endpoints-prom-exporter
      containers:
      - name: endpoints-prom-exporter
        image: andreistefanciprian/endpoints-prom-exporter:2
        env:
          - name: EXPORTER_PORT
            value: "9153"
---            
apiVersion: v1
kind: Service
metadata:
  name: endpoints-prom-exporter
  labels:
    app: endpoints-prom-exporter
  # annotations:
  #   prometheus.io/port: "9153"
  #   prometheus.io/scrape: "true"
spec:
  selector:
    app: endpoints-prom-exporter
  ports:
    - name: prom
      port: 9153
      targetPort: 9153
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: endpoints-prom-exporter
  labels:
    release: prom
spec:
  endpoints:
  - interval: 5s
    # targetPort: prom
    port: prom
    path: /metrics
  selector:
    matchLabels:
      app: endpoints-prom-exporter
  namespaceSelector:
    matchNames:
    - default