apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoints-prom-exporter
  labels:
    app: endpoints-prom-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoints-prom-exporter
  template:
    metadata:
      labels:
        app: endpoints-prom-exporter
    spec:
      serviceAccountName: endpoints-prom-exporter
      containers:
      - name: endpoints-prom-exporter
        image: andreistefanciprian/endpoints-prom-exporter:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "python main.py --service-name foo --namespace-name default --polling-interval 2"]
        env:
          - name: EXPORTER_PORT
            value: "9153"
          - name: KUBE_AUTH_INSIDE_CLUSTER
            value: "True"
---            
apiVersion: v1
kind: Service
metadata:
  name: endpoints-prom-exporter
  labels:
    app: endpoints-prom-exporter
spec:
  selector:
    app: endpoints-prom-exporter
  ports:
    - name: prom
      port: 9153
      targetPort: 9153
      protocol: TCP