apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: endpoints-prom-exporter
  labels:
    release: prom
spec:
  endpoints:
  - interval: 5s
    # targetPort: prom
    port: prom
    path: /metrics
  selector:
    matchLabels:
      app: endpoints-prom-exporter
  namespaceSelector:
    matchNames:
    - default